name: Deploy to GH Pages

env: 
    VUE_APP_API_KEY: ${{secrets.API_KEY}}

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Install 
        run: yarn install

      - name: Build 
        run: yarn build
        env:
          NODE_ENV: production
          VUE_APP_API_KEY: ${{secrets.API_KEY}}

      - name: Deploy to GH Pages 
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist